-- drop the parent schema and all of its tables
DROP TABLE IF EXISTS IGNORED;
DROP TABLE IF EXISTS FRIEND;
DROP TABLE IF EXISTS PLAYER_APPEARANCE;
DROP TABLE IF EXISTS PLAYER_EQUIPMENT;
DROP TABLE IF EXISTS PLAYER;
