# configuration for the game server
server:
  # the hostname or IP address the server will listen on
  host: 0.0.0.0
  # the port number the server will listen on
  port: 43594
  # unique game world identifier
  worldId: 69
  # directory where game assets are located
  assetDir: data
  # directory where game scripts are located
  scriptsDir: ./scripts
  # message sent to players when they log in
  welcomeMessage: Welcome to OpenMCS!
  # verbosity for logging (debug, info, error)
  logLevel: info

# configuration for metrics and observability data
metrics:
  # control if metrics are collected or not
  enabled: true
  # the port number for exposing metrics
  port: 2112

# configuration for persistent storage
store:
  # directory containing schema migrations
  migrationsDir: migrations/sqlite3
  # the type of storage driver (sqlite3)
  driver: sqlite3
  # configuration for a SQLite3 database
  sqlite3:
    # the URI for the database connection
    uri: data/game.db

# configuration for game interface
interfaces:
  # character designer interface
  characterDesigner:
    id: 3559
  # primary inventory tab interface
  inventory:
    id: 3213
    slots: 3214
  # equipment tab interface and child interface for bonuses
  equipment:
    id: 1644
    slots: 1688
