{
 "title": "OpenMCS - Server",
 "description": "Metrics for an OpenMCS server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Game State Update Time",
   "type": "timeseries",
   "description": "The amount of time game state updates take to complete.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(game_state_update_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "description": "Total number of connected players.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "users_online_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tick Count",
   "type": "stat",
   "description": "The number of ticks the server has processed.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "game_state_update_duration_count{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Used Bytes Allocated",
   "type": "timeseries",
   "description": "Total number of bytes allocated in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "Bytes In Use" },
    {
     "expr": "go_memstats_alloc_bytes_total{}",
     "legendFormat": "Bytes Total"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "Num Goroutines" }
   ]
  }
 ]
}