-------------------------------------
-- Globals
-------------------------------------

-- identifiers for client tabs
CLIENT_TAB_EQUIPPED_ITEM = 0
CLIENT_TAB_SKILLS = 1
CLIENT_TAB_QUESTS = 2
CLIENT_TAB_INVENTORY = 3
CLIENT_TAB_EQUIPMENT = 4
CLIENT_TAB_PRAYERS = 5
CLIENT_TAB_SPELLS = 6
CLIENT_TAB_FRIENDS_LIST = 7
CLIENT_TAB_IGNORE_LIST = 8
CLIENT_TAB_LOGOUT = 9
CLIENT_TAB_SETTINGS = 10
CLIENT_TAB_CONTROLS = 11
CLIENT_TAB_MUSIC = 12

-- identifiers for equipment slots
EQUIP_SLOT_HEAD = 0
EQUIP_SLOT_CAPE = 1
EQUIP_SLOT_NECKLACE = 2
EQUIP_SLOT_WEAPON = 3
EQUIP_SLOT_BODY = 4
EQUIP_SLOT_SHIELD = 5
EQUIP_SLOT_LEGS = 7
EQUIP_SLOT_HANDS = 9
EQUIP_SLOT_FEET = 10
EQUIP_SLOT_RING = 12
EQUIP_SLOT_AMMO = 13

-- identifiers for weapon styles
WEAPON_STYLE_UNARMED = 0
WEAPON_STYLE_2H_SWORD = 1
WEAPON_STYLE_AXE = 2
WEAPON_STYLE_BOW = 3
WEAPON_STYLE_BLUNT = 4
WEAPON_STYLE_CLAW = 5
WEAPON_STYLE_CROSSBOW = 6
WEAPON_STYLE_GUN = 7
WEAPON_STYLE_PICKAXE = 8
WEAPON_STYLE_POLEARM = 9
WEAPON_STYLE_POLESTAFF = 10
WEAPON_STYLE_SCYTHE = 11
WEAPON_STYLE_SLASH_SWORD = 12
WEAPON_STYLE_SPEAR = 13
WEAPON_STYLE_SPIKED = 14
WEAPON_STYLE_STAB_SWORD = 14
WEAPON_STYLE_STAFF = 15
WEAPON_STYLE_THROWN = 16
WEAPON_STYLE_WHIP = 17

-- identifiers for combat stats
STAT_ATTACK_STAB = 0
STAT_ATTACK_SLASH = 1
STAT_ATTACK_CRUSH = 2
STAT_ATTACK_MAGIC = 3
STAT_ATTACK_RANGE = 4
STAT_DEFENSE_STAB = 5
STAT_DEFENSE_SLASH = 6
STAT_DEFENSE_CRUSH = 7
STAT_DEFENSE_MAGIC = 8
STAT_DEFENSE_RANGE = 9
STAT_STRENGTH = 10
STAT_PRAYER = 11

-- identifiers for weapon attack styles
ATTACK_STYLE_CHOP = 0
ATTACK_STYLE_SLASH = 1
ATTACK_STYLE_LUNGE = 2
ATTACK_STYLE_BLOCK = 3
ATTACK_STYLE_PUNCH = 4
ATTACK_STYLE_KICK = 5
ATTACK_STYLE_POUND = 6
ATTACK_STYLE_PUMMEL = 7
ATTACK_STYLE_SPIKE = 8
ATTACK_STYLE_IMPALE = 9
ATTACK_STYLE_SMASH = 10
ATTACK_STYLE_JAB = 11
ATTACK_STYLE_SWIPE = 12
ATTACK_STYLE_FEND = 13
ATTACK_STYLE_BASH = 14
ATTACK_STYLE_REAP = 15
ATTACK_STYLE_FLICK = 16
ATTACK_STYLE_LASH = 17
ATTACK_STYLE_DEFLECT = 18
ATTACK_STYLE_ACCURATE = 19
ATTACK_STYLE_RAPID = 20
ATTACK_STYLE_LONG_RANGE = 21
ATTACK_STYLE_ARM_AND_FIRE = 22
ATTACK_STYLE_FOCUS = 23
ATTACK_STYLE_STAB = 24

-- identifiers for skills
SKILL_ATTACK = 0
SKILL_DEFENSE = 1
SKILL_STRENGTH = 2
SKILL_HITPOINTS = 3
SKILL_RANGED = 4
SKILL_PRAYER = 5
SKILL_MAGIC = 6
SKILL_COOKING = 7
SKILL_WOODCUTTING = 8
SKILL_FLETCHING = 9
SKILL_FISHING = 10
SKILL_FIREMAKING = 11
SKILL_CRAFTING = 12
SKILL_SMITH = 13
SKILL_MINING = 14
SKILL_HERBLORE = 15
SKILL_AGILITY = 16
SKILL_THIEVING = 17
SKILL_SLAYER = 18
SKILL_FARMING = 19
SKILL_RUNECRAFT = 20

-- identifiers for game options
GAME_OPTION_SCREEN_BRIGHTNESS = 0
GAME_OPTION_MOUSE_BUTTONS = 1
GAME_OPTION_CHAT_EFFECTS = 2
GAME_OPTION_SPLIT_PRIVATE_CHAT = 3
GAME_OPTION_ACCEPT_AID = 4
GAME_OPTION_MUSIC_VOLUME = 5
GAME_OPTION_EFFECTS_VOLUME = 6

-- screen brightness options
SCREEN_BRIGHTNESS_DARK = "DARK"
SCREEN_BRIGHTNESS_NORMAL = "NORMAL"
SCREEN_BRIGHTNESS_BRIGHT = "BRIGHT"
SCREEN_BRIGHTNESS_VERY_BRIGHT = "VERY_BRIGHT"

-- mouse button options
MOUSE_BUTTONS_ONE = "ONE"
MOUSE_BUTTONS_TWO = "TWO"

-- chat effects options
CHAT_EFFECTS_ON = "ON"
CHAT_EFFECTS_OFF = "OFF"

-- split private chat options
SPLIT_PRIVATE_CHAT_ON = "ON"
SPLIT_PRIVATE_CHAT_OFF = "OFF"

-- accept aid options
ACCEPT_AID_YES = "YES"
ACCEPT_AID_NO = "NO"

-- movement speeds
MOVE_SPEED_WALK = 0
MOVE_SPEED_RUN = 1

-- overhead icons
OVERHEAD_NONE = 0
OVERHEAD_PROTECT_FROM_MELEE = 1
OVERHEAD_PROTECT_FROM_MISSILES = 2
OVERHEAD_PROTECT_FROM_MAGE = 4
OVERHEAD_RETRIBUTION = 8
OVERHEAD_SMITE = 16
OVERHEAD_REDEMPTION = 32
OVERHEAD_WHITE_SKULL = 64
OVERHEAD_RED_SKULL = 128

-- identifiers for quest statuses
QUEST_STATUS_NOT_STARTED = 0
QUEST_STATUS_IN_PROGRESS = 1
QUEST_STATUS_COMPLETED = 2

-- change events
CHANGE_RUN_ENERGY = 0
CHANGE_PRAYER_EXHAUSTED = 1