-------------------------------------
-- Prayers
-------------------------------------

-- identifiers for prayers
PRAYER_THICK_SKIN = 0
PRAYER_BURST_OF_STRENGTH = 1
PRAYER_CLARITY_OF_THOUGHT = 2
PRAYER_ROCK_SKIN = 3
PRAYER_SUPERHUMAN_STRENGTH = 4
PRAYER_IMPROVED_REFLEXES = 5
PRAYER_RAPID_RESTORE = 6
PRAYER_RAPID_HEAL = 7
PRAYER_PROTECT_ITEMS = 8
PRAYER_STEEL_SKIN = 9
PRAYER_ULTIMATE_STRENGTH = 10
PRAYER_INCREDIBLE_REFLEXES = 11
PRAYER_PROTECT_FROM_MAGE = 12
PRAYER_PROTECT_FROM_MISSILES = 13
PRAYER_PROTECT_FROM_MELEE = 14
PRAYER_RETRIBUTION = 15
PRAYER_REDEMPTION = 16
PRAYER_SMITE = 17


