global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:2112']
  - job_name: openmcs-server
    metrics_path: /metrics
