-------------------------------------
-- Globals
-------------------------------------

-- identifiers for client tabs
CLIENT_TAB_EQUIPPED_ITEM = 0
CLIENT_TAB_SKILLS = 1
CLIENT_TAB_QUESTS = 2
CLIENT_TAB_INVENTORY = 3
CLIENT_TAB_EQUIPMENT = 4
CLIENT_TAB_PRAYERS = 5
CLIENT_TAB_SPELLS = 6
CLIENT_TAB_FRIENDS_LIST = 7
CLIENT_TAB_IGNORE_LIST = 8
CLIENT_TAB_LOGOUT = 9
CLIENT_TAB_SETTINGS = 10
CLIENT_TAB_CONTROLS = 11
CLIENT_TAB_MUSIC = 12

-- identifiers for weapon styles
WEAPON_STYLE_NONE = 0
WEAPON_STYLE_2H_SWORD = 1
WEAPON_STYLE_AXE = 2
WEAPON_STYLE_BOW = 3
WEAPON_STYLE_BLUNT = 4
WEAPON_STYLE_CLAW = 5
WEAPON_STYLE_CROSSBOW = 6
WEAPON_STYLE_GUN = 7
WEAPON_STYLE_PICKAXE = 8
WEAPON_STYLE_POLEARM = 9
WEAPON_STYLE_POLESTAFF = 10
WEAPON_STYLE_SCYTHE = 11
WEAPON_STYLE_SLASH_SWORD = 12
WEAPON_STYLE_SPEAR = 13
WEAPON_STYLE_SPIKED = 14
WEAPON_STYLE_STAB_SWORD = 14
WEAPON_STYLE_STAFF = 15
WEAPON_STYLE_THROWN = 16
WEAPON_STYLE_WHIP = 17
