-------------------------------------
-- Globals
-------------------------------------

-- identifiers for client tabs
CLIENT_TAB_EQUIPPED_ITEM = 0
CLIENT_TAB_SKILLS = 1
CLIENT_TAB_QUESTS = 2
CLIENT_TAB_INVENTORY = 3
CLIENT_TAB_EQUIPMENT = 4
CLIENT_TAB_PRAYERS = 5
CLIENT_TAB_SPELLS = 6
CLIENT_TAB_FRIENDS_LIST = 7
CLIENT_TAB_IGNORE_LIST = 8
CLIENT_TAB_LOGOUT = 9
CLIENT_TAB_SETTINGS = 10
CLIENT_TAB_CONTROLS = 11
CLIENT_TAB_MUSIC = 12

-- identifiers for equipment slots
EQUIP_SLOT_HEAD = 0
EQUIP_SLOT_CAPE = 1
EQUIP_SLOT_NECKLACE = 2
EQUIP_SLOT_WEAPON = 3
EQUIP_SLOT_BODY = 4
EQUIP_SLOT_SHIELD = 5
EQUIP_SLOT_LEGS = 7
EQUIP_SLOT_HANDS = 9
EQUIP_SLOT_FEET = 10
EQUIP_SLOT_RING = 12
EQUIP_SLOT_AMMO = 13

-- identifiers for weapon styles
WEAPON_STYLE_UNARMED = 0
WEAPON_STYLE_2H_SWORD = 1
WEAPON_STYLE_AXE = 2
WEAPON_STYLE_BOW = 3
WEAPON_STYLE_BLUNT = 4
WEAPON_STYLE_CLAW = 5
WEAPON_STYLE_CROSSBOW = 6
WEAPON_STYLE_GUN = 7
WEAPON_STYLE_PICKAXE = 8
WEAPON_STYLE_POLEARM = 9
WEAPON_STYLE_POLESTAFF = 10
WEAPON_STYLE_SCYTHE = 11
WEAPON_STYLE_SLASH_SWORD = 12
WEAPON_STYLE_SPEAR = 13
WEAPON_STYLE_SPIKED = 14
WEAPON_STYLE_STAB_SWORD = 14
WEAPON_STYLE_STAFF = 15
WEAPON_STYLE_THROWN = 16
WEAPON_STYLE_WHIP = 17

-- identifiers for combat stats
STAT_ATTACK_STAB = 0
STAT_ATTACK_SLASH = 1
STAT_ATTACK_CRUSH = 2
STAT_ATTACK_MAGIC = 3
STAT_ATTACK_RANGE = 4
STAT_DEFENSE_STAB = 5
STAT_DEFENSE_SLASH = 6
STAT_DEFENSE_CRUSH = 7
STAT_DEFENSE_MAGIC = 8
STAT_DEFENSE_RANGE = 9
STAT_STRENGTH = 10
STAT_PRAYER = 11

-- identifiers for weapon attack styles
ATTACK_STYLE_CHOP = 0
ATTACK_STYLE_SLASH = 1
ATTACK_STYLE_LUNGE = 2
ATTACK_STYLE_BLOCK = 3
ATTACK_STYLE_PUNCH = 4
ATTACK_STYLE_KICK = 5